__author__ = 'Matthew Thode'
__contact__ = 'Matthew Thode'
__email__ = 'mthode@mthode.org'
__copyright__ = '2014 All Rights Reserved'
__license__ = 'Apache2'
__date__ = '2014-10-27'
__version__ = '0.1.0'
__status__ = 'Production'
__appname__ = 'binarytree_test'
__description__ = 'simple api for verifying if a binary tree'
' is a subtree of another binary tree'
